### ISSUE TITLE
BigInt not supported but it has been since v4

### ISSUE THREAD

**Issue by dan-online** [yahoo/serialize-javascript#125]
```js
Node 16.0.0
Serialize-Javascript 6.0.0
Typescript 4.3.4
```

I ran into this error today, my first idea is that "BigInt" is weird because I'm using typescript? 

Example data: ``{ big: BigInt(0) }``

Error:

```js
str = JSON.stringify(obj, options.isJSON ? null : replacer, options.space);
                   ^
TypeError: Do not know how to serialize a BigInt
```

**Comment by dan-online** [comment]
This repo seems quiet so I'll just post why and close:

Because ``big`` is nested in an object, it doesn't go deeper and so BigInt is never serialized

**Comment by momocow** [comment]
Nop, it **DOES** go deeper with `replacer`; however, no other bigint but `0n` passes through the replacer without being serialized due to the following condition, which returns the `0n` directly.

https://github.com/yahoo/serialize-javascript/blob/343abd98ff0a3f88f61fca35100762fdd6cb1963/index.js#L86-L88

Other bigints are serialized as expected.

Also see #154
